[
    {
        "message": "testhyp",
        "model_trainer":{
            "class": "keras_model_trainer.KerasFitGeneratorModelTrainer",
            "kwargs": {
                "seed": 234,
                "samples_per_epoch": 2000,
                "stopping_criterion_config": {
                    "class": "EarlyStopping" ,
                    "kwargs": {
                       "max_epochs": 300,
                       "epochs_to_wait": 3
                    }
                },
                "class_weight": {"0":1, "1":10}
            }
        },
        "model_creator":{
            "class": "flexible_keras.FlexibleKerasSequential",
            "kwargs": {
                "pretrained_model_config": {
                    "weight_file": "dan_basset_keras_port.weights.h5",
                    "json_file": "dan_basset_keras_port.arch.json",
                    "last_layer_to_take": -3,
                    #"last_layer_to_fix": -11 
                },
                "layers_config": [
                    {
                        "class": "keras.layers.core.Dense",
                        "kwargs": {
                            "output_dim": 1000,
                            "name": "dense_1_fromscratch"
                        }
                    },
                    {
                        "class": "keras.layers.normalization.BatchNormalization",
                        "kwargs": {"name": "batchnorm_1_fromscratch"}
                    },
                    {
                        "class": "keras.layers.Activation",
                        "kwargs": {"activation": "relu",
                                   "name": "activation_1_fromscratch"}
                    },
                    {
                        "class": "keras.layers.core.Dropout",
                        "kwargs": {"p": 0.3,
                                   "name": "dropout_1_fromscratch"}
                    },
                    {
                        "class": "keras.layers.core.Dense",
                        "kwargs": {
                            "output_dim": 1000,
                            "name": "dense_2_fromscratch"
                        }
                    },
                    {
                        "class": "keras.layers.normalization.BatchNormalization",
                        "kwargs": {"name": "batchnorm_2_fromscratch"}
                    },
                    {
                        "class": "keras.layers.Activation",
                        "kwargs": {"activation": "relu",
                                   "name": "activation_2_fromscratch"}
                    },
                    {
                        "class": "keras.layers.core.Dropout",
                        "kwargs": {"p": 0.3,
                                   "name": "dropout_2_fromscratch"}
                    },
                    {
                        "class": "keras.layers.core.Dense",
                        "kwargs": {
                            "output_dim": 1,
                            "name": "dense_3_fromscratch"
                        }
                    },
                    {
                        "class": "keras.layers.core.Activation",
                        "kwargs": {"activation": "sigmoid",
                                   "name": "output"}
                     }
                ],
                "optimizer_config": {
                    "class": "keras.optimizers.Adam",
                    "kwargs": {"lr": 0.0001}
                },
                "loss": {
                    "modules_to_load": ["keras_genomics"],
                    "func": "keras_genomics.losses.ambig_binary_crossentropy"
                }
            }
        },
        "other_data_loaders":{
            "train": {
                "class": "pyfasta_data_loader.TwoStreamSeqOnly",
                "kwargs": {
                   "batch_size": 200,
                   "positives_bed_source": "naive_window_around_summit.bed.gz",
                   "negatives_bed_source": "naive_window_around_summit.bed.gz",
                   "negatives_to_positives_ratio": 10,
                   "fasta_data_source": "/mnt/data/annotations/by_organism/human/hg19.GRCh37/hg19.genome.fa",
                   "rc_augment": true,
                   "num_to_load_for_eval": 50000,
                   "labels_dtype": "int"
                }
            }
        },
    },
]
